
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'inicioCORCHETE_DER CORCHETE_IZQ ID MAS MENOS NUMERO PUNTOYCOMA TIPOinicio : lista_expresioneslista_expresiones : lista_expresiones expresionlista_expresiones : expresionexpresion : TIPO ID PUNTOYCOMAexpresion : TIPO ID CORCHETE_IZQ NUMERO CORCHETE_DER PUNTOYCOMAexpresion : expresion MAS terminoexpresion : expresion MENOS terminoexpresion : terminotermino : NUMEROtermino : ID'
    
_lr_action_items = {'TIPO':([0,2,3,5,6,7,8,12,13,14,18,],[4,4,-3,-10,-9,-8,-2,-6,-7,-4,-5,]),'NUMERO':([0,2,3,5,6,7,8,9,10,12,13,14,15,18,],[6,6,-3,-10,-9,-8,-2,6,6,-6,-7,-4,16,-5,]),'ID':([0,2,3,4,5,6,7,8,9,10,12,13,14,18,],[5,5,-3,11,-10,-9,-8,-2,5,5,-6,-7,-4,-5,]),'$end':([1,2,3,5,6,7,8,12,13,14,18,],[0,-1,-3,-10,-9,-8,-2,-6,-7,-4,-5,]),'MAS':([3,5,6,7,8,12,13,14,18,],[9,-10,-9,-8,9,-6,-7,-4,-5,]),'MENOS':([3,5,6,7,8,12,13,14,18,],[10,-10,-9,-8,10,-6,-7,-4,-5,]),'PUNTOYCOMA':([11,17,],[14,18,]),'CORCHETE_IZQ':([11,],[15,]),'CORCHETE_DER':([16,],[17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,],[1,]),'lista_expresiones':([0,],[2,]),'expresion':([0,2,],[3,8,]),'termino':([0,2,9,10,],[7,7,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> lista_expresiones','inicio',1,'p_inicio','analizador_sintactico.py',8),
  ('lista_expresiones -> lista_expresiones expresion','lista_expresiones',2,'p_lista_expresiones_multiple','analizador_sintactico.py',12),
  ('lista_expresiones -> expresion','lista_expresiones',1,'p_lista_expresiones_una','analizador_sintactico.py',16),
  ('expresion -> TIPO ID PUNTOYCOMA','expresion',3,'p_declaracion_variable','analizador_sintactico.py',31),
  ('expresion -> TIPO ID CORCHETE_IZQ NUMERO CORCHETE_DER PUNTOYCOMA','expresion',6,'p_declaracion_arreglo','analizador_sintactico.py',40),
  ('expresion -> expresion MAS termino','expresion',3,'p_expresion_suma','analizador_sintactico.py',50),
  ('expresion -> expresion MENOS termino','expresion',3,'p_expresion_resta','analizador_sintactico.py',57),
  ('expresion -> termino','expresion',1,'p_expresion_termino','analizador_sintactico.py',64),
  ('termino -> NUMERO','termino',1,'p_termino_numero','analizador_sintactico.py',69),
  ('termino -> ID','termino',1,'p_termino_id','analizador_sintactico.py',74),
]
